[package]
name = "seraph"
version = "0.1.0"
edition = "2024"

[dependencies]
seraph_backend = { path = "./seraph_backend" }
migration = { path = "./migration" }


[workspace]
members = [".", "seraph_backend", "migration"]
