x-base: &base
  image: udi/seraph:latest
  build:
    context: .
    dockerfile: ./Dockerfile
  restart: always
  depends_on:
    - redis
    - postgres
    # - rabbitmq
  environment:
    # General Envs
    ENV: ${ENV}
    LOGGING_TYPE: ${LOGGING_TYPE}
    # Logstash Envs
    LOGSTASH_HOST: ${LOGSTASH_HOST}
    LOGSTASH_SSL_ENABLED: ${LOGSTASH_SSL_ENABLED}
    LOGSTASH_PORT: ${LOGSTASH_PORT}
    # Http Server
    SERVER_ADDRESS: ${SERVER_ADDRESS}
    SERVER_PORT: ${SERVER_PORT}
    # Database Envs
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_SCHEMA: ${DATABASE_SCHEMA}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Redis Envs
    REDIS_HOST: ${REDIS_HOST}
    REDIS_PORT: ${REDIS_PORT}
  networks:
    - "seraph"

services:
  seraph:
    <<: *base
    command: "./target/release/seraph"
    ports:
      - "5000:5000"

  seraph-worker:
    <<: *base
    command: "./target/release/code_nodes_consumer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:17.4
    ports:
      - "5432:5432"
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - "seraph"
  # pgadmin4:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "test@test.com"
  #     PGADMIN_DEFAULT_PASSWORD: "mysecretpassword"
  #     PGADMIN_LISTEN_PORT: 8888
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - pg-admin-data:/var/lib/pgadmin
  #   networks:
  #     - "seraph"

  redis:
    image: redis/redis-stack-server:7.4.0-v1
    ports:
      - "6379:6379"
    restart: always
    networks:
      - "seraph"

  # rabbitmq:
  #   image: dcoya/seraph-rabbitmq:latest
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - "5673:5673"
  #     - "15673:15673"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   restart: always
  #   networks:
  #     - "seraph"

volumes:
  postgres-data:
  pg-admin-data:


networks:
  seraph:
